[program:chromium]
command=/usr/local/bin/chromium-launcher --headless
autostart=false
autorestart=true
startsecs=0
stopsignal=KILL
stopasgroup=true
killasgroup=true
stopwaitsecs=1
stdout_logfile=/var/log/supervisord/chromium
redirect_stderr=true
