[program:pulseaudio]
command=/bin/bash -lc '/usr/local/bin/start-pulseaudio.sh'
autostart=false
autorestart=true
startsecs=0
exitcodes=0
stdout_logfile=/var/log/supervisord/pulseaudio
redirect_stderr=true
